// Code generated by "generr"; DO NOT EDIT.
package rmoc

import "fmt"

func IsFileAlreadyExists(err error) (bool, string) {
	var filename string
	if e, ok := err.(fileAlreadyExists); ok {
		filename = e.FileAlreadyExists()
		return true, filename
	}
	return false, filename
}

type FileAlreadyExists struct {
	Filename string
}

func (e *FileAlreadyExists) FileAlreadyExists() string {
	return e.Filename
}
func (e *FileAlreadyExists) Error() string {
	return fmt.Sprintf("fileAlreadyExists Filename: %v", e.Filename)
}
